import Head from 'next/head'
import HomeMaxIcon from '@mui/icons-material/HomeMax';
import TwitterIcon from '@mui/icons-material/Twitter';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import Image from 'next/image'
import esti from '../public/images/esti.png' 


export default function Home() {
  return (
    <div>
      <Head>
        <title>EstebanFranco.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 '>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons cursor-pointer'>Esteban Franco</h1>
            <ul className=' flex items-center'>
              <li><HomeMaxIcon className=' cursor-pointer' /></li>
              <li>
                <a 
                  className=' bg-gradient-to-r from-cyan-500 to-blue-500 text-white px-4 py-2 rounded'
                  href='https://www.linkedin.com/in/estebanneorenfranco'
                >
                  Resume
                </a>
              </li>            
            </ul>
          </nav>
          <div className=' text-center p-10 '>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium '>EstebanFranco</h2>
            <h3 className='text-2xl py-2  '>Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 '>Soy tecnico electronico y estoy estudiando la licenciatura en Gestión de Negocios en ITBA. </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 '>
              <TwitterIcon/>
              <LinkedInIcon/>
          </div>
          <div className='relative mx-auto  rounded-full w-25 h-25 mt-20 '>
            <Image  src={esti} layout="fill" objectFit='cover' />
          </div>  
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>About me:</h3>
            <p className=''>
            Desde chico me apasiona la tecnología, a los 12 me regalaron un Arduino y desde entonces desarrollar proyectos tecnológicos es la actividad que más me apasiona.
            </p>
            <p className=''>
            Con el objetivo de crear proyectos innovadores con el objetivo de presentarlos en diferentes concursos, hoy en día, cuento con conocimiento en el uso de Machine Learning, programación de microcontroladores, desarrollo web y de apps.
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}


//minuto 29:00


//https://www.youtube.com/watch?v=QNTeq4QdOsQ